import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const poppins = Poppins({
  weight: ['400', '500'],
   subsets: ["latin"],
   variable: '--poppins'
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="bg-beige font-pText">
        <Header />
        {children}
        </body>
    </html>
  );
}
